In [ ]:
import pandas as pd

import numpy as np

In [ ]:
n1 = np.array([[2,1,4,3],[4,5,6,2],[3,5,4,6]])
print(n1)

[[2 1 4 3]
 [4 5 6 2]
 [3 5 4 6]]


In [ ]:
n2 = np.array([[2,1,4,3],[4,5,6,2],[3,5,4.1,6]])
print(n2)

[[2.  1.  4.  3. ]
 [4.  5.  6.  2. ]
 [3.  5.  4.1 6. ]]


In [ ]:
n3 = np.array([[2,1,4,3],[4,'5',6,2],[3,5,4.1,6]])
print(n3)

[['2' '1' '4' '3']
 ['4' '5' '6' '2']
 ['3' '5' '4.1' '6']]


In [ ]:
d1 = pd.DataFrame(n1)
d1.columns = ['a','b','c','d']
d1.index = ['r1','r2','r3']
d1

a  b  c  d
r1  2  1  4  3
r2  4  5  6  2
r3  3  5  4  6

In [ ]:
d1.dtypes

a    int64
b    int64
c    int64
d    int64
dtype: object

In [ ]:
d1['b'] = [1 , 5.0 , 5]

In [ ]:
d1

a    b  c  d
r1  2  1.0  4  3
r2  4  5.0  6  2
r3  3  5.0  4  6

In [ ]:
d1.dtypes

a      int64
b    float64
c      int64
d      int64
dtype: object

In [ ]:
d1['c'] = [4,'6',4]
d1

a    b  c  d
r1  2  1.0  4  3
r2  4  5.0  6  2
r3  3  5.0  4  6

In [ ]:
d1.dtypes

a      int64
b    float64
c     object
d      int64
dtype: object

* Numpy - Homogeneous Data Structure
* Pandas - Homogeneous Data column

In [ ]:
students_data = {"Name": ['Atul', 'Aman' , 'Pavan' , 'Nikhil' , 'Raman'],
                 "Age": [10,12,14,11,13],
                 "City": ['Delhi','Mumbai','Delhi' , 'Delhi' , 'Mumbai']}
print(students_data)

{'Name': ['Atul', 'Aman', 'Pavan', 'Nikhil', 'Raman'], 'Age': [10, 12, 14, 11, 13], 'City': ['Delhi', 'Mumbai', 'Delhi', 'Delhi', 'Mumbai']}


In [ ]:
d2 = pd.DataFrame(students_data)
d2

Name  Age    City
0    Atul   10   Delhi
1    Aman   12  Mumbai
2   Pavan   14   Delhi
3  Nikhil   11   Delhi
4   Raman   13  Mumbai

In [ ]:
d2.loc[1,'Name'] = 'Ajay'

In [ ]:
d2

Name  Age    City
0    Atul   10   Delhi
1    Ajay   12  Mumbai
2   Pavan   14   Delhi
3  Nikhil   11   Delhi
4   Raman   13  Mumbai