**Slicing in Numpy**

In [ ]:
import numpy as np

n1 = np.arange(0,36)        #array + range
print(n1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


In [ ]:
#36 - (1,36),(36,1),(2,18),(18,2),(3,12),(12,3),(4,9),(9,4),(6,6)

n2 = n1.reshape(6,6)
print(n2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [ ]:
n2[2:5 , 2:6]

array([[14, 15, 16, 17],
       [20, 21, 22, 23],
       [26, 27, 28, 29]])

In [ ]:
n2[2:6,1:3]

array([[13, 14],
       [19, 20],
       [25, 26],
       [31, 32]])

In [ ]:
print(n2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [ ]:
n2.shape

(6, 6)

In [ ]:
n2[3: , :]

array([[18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
n2[5: , :]

array([[30, 31, 32, 33, 34, 35]])

In [ ]:
n2[-1: , :]

array([[30, 31, 32, 33, 34, 35]])

In [ ]:
n2[-2: , :]

array([[24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
n2[:,-1:]

array([[ 5],
       [11],
       [17],
       [23],
       [29],
       [35]])

**Broadcasting**

In [ ]:
n3 = np.array([[1,2,3,4],[5,6,7,8],[2,4,6,8]])
print(n3)

[[1 2 3 4]
 [5 6 7 8]
 [2 4 6 8]]


In [ ]:
k1 = 3

print(n3 * k1)

[[ 3  6  9 12]
 [15 18 21 24]
 [ 6 12 18 24]]


In [ ]:
k2 = [2,3,4,2]

print(n3 * k2)

[[ 2  6 12  8]
 [10 18 28 16]
 [ 4 12 24 16]]


In [ ]:
print(n3)

[[1 2 3 4]
 [5 6 7 8]
 [2 4 6 8]]


In [ ]:
k3 = np.array([[2],[3],[2]])

print(k3)

[[2]
 [3]
 [2]]


In [ ]:
print(n3*k3)

[[ 2  4  6  8]
 [15 18 21 24]
 [ 4  8 12 16]]


In [ ]:
print(n3)

[[1 2 3 4]
 [5 6 7 8]
 [2 4 6 8]]


In [ ]:
kx = np.array([[2,3],[1,2],[2,1]])
print(kx)

[[2 3]
 [1 2]
 [2 1]]


In [ ]:
print(n3*kx)

ValueError: operands could not be broadcast together with shapes (3,4) (3,2) 

**Linear Algebra Operations**

In [ ]:
a = np.array([[2,3,4],[1,3,4]])
print(a)

[[2 3 4]
 [1 3 4]]


In [ ]:
b = np.array([[1,3,2],[2,2,1]])
print(b)

[[1 3 2]
 [2 2 1]]


In [ ]:
np.transpose(b)

array([[1, 2],
       [3, 2],
       [2, 1]])

In [ ]:
np.dot(a,np.transpose(b))

array([[19, 14],
       [18, 12]])

* 3x + 2y + z = 10
* 2x + y + 5z = 15
* x + y + z = 5

In [ ]:
A = np.array([[3,2,1] , [2,1,5] , [1,1,1]])
print(A)

[[3 2 1]
 [2 1 5]
 [1 1 1]]


In [ ]:
X = np.array([['x'],['y'],['z']])
print(X)

[['x']
 ['y']
 ['z']]


In [ ]:
B = np.array([[10],[15],[5]])
print(B)

[[10]
 [15]
 [ 5]]


In [ ]:
Ainv = np.linalg.inv(A)
print(Ainv)

[[ 0.8  0.2 -1.8]
 [-0.6 -0.4  2.6]
 [-0.2  0.2  0.2]]


In [ ]:
X = np.dot(Ainv,B)
print(X)

[[2.]
 [1.]
 [2.]]


In [ ]:
np.dot(A,X)

array([[10.],
       [15.],
       [ 5.]])