In [ ]:
l1 = [3,4,5,6,7,2]
print(l1 * 2)

[3, 4, 5, 6, 7, 2, 3, 4, 5, 6, 7, 2]


In [ ]:
import numpy as np

n1 = np.array([3,4,5,6,7,2])
print(n1 * 2)

[ 6  8 10 12 14  4]


In [ ]:
l2 = [[2,3,4,5,6] , [4,6,3,2,1] , [7,6,5,4,3]]
print(l2)

[[2, 3, 4, 5, 6], [4, 6, 3, 2, 1], [7, 6, 5, 4, 3]]


In [ ]:
n2 = np.array([[2,3,4,5,6] , [4,6,3,2,1] , [7,6,5,4,3]])
print(n2)

[[2 3 4 5 6]
 [4 6 3 2 1]
 [7 6 5 4 3]]


In [ ]:
print(np.sum(n2))
print(np.mean(n2))
print(np.median(n2))
print(np.std(n2))
print(np.var(n2))
print(np.min(n2))
print(np.max(n2))
print(np.argmin(n2))
print(np.argmax(n2))

61
4.066666666666666
4.0
1.6918103387266028
2.8622222222222224
1
7
9
10


In [ ]:
print(n2)

[[2 3 4 5 6]
 [4 6 3 2 1]
 [7 6 5 4 3]]


In [ ]:
print(n2.shape)
print(n2.ndim)
print(n2.size)

(3, 5)
2
15


In [ ]:
#Perform calculation for each data row

print(np.sum(n2 , axis=1))
print(np.mean(n2 , axis=1))
print(np.median(n2 , axis=1))
print(np.std(n2 , axis=1))
print(np.var(n2 , axis=1))
print(np.min(n2 , axis=1))
print(np.max(n2 , axis=1))
print(np.argmin(n2 , axis=1))
print(np.argmax(n2 , axis=1))

[20 16 25]
[4.  3.2 5. ]
[4. 3. 5.]
[1.41421356 1.72046505 1.41421356]
[2.   2.96 2.  ]
[2 1 3]
[6 6 7]
[0 4 4]
[4 1 0]


In [ ]:
#Perform calculation for each data column

print(np.sum(n2 , axis=0))
print(np.mean(n2 , axis=0))
print(np.median(n2 , axis=0))
print(np.std(n2 , axis=0))
print(np.var(n2 , axis=0))
print(np.min(n2 , axis=0))
print(np.max(n2 , axis=0))
print(np.argmin(n2 , axis=0))
print(np.argmax(n2 , axis=0))

[13 15 12 11 10]
[4.33333333 5.         4.         3.66666667 3.33333333]
[4. 6. 4. 4. 3.]
[2.05480467 1.41421356 0.81649658 1.24721913 2.05480467]
[4.22222222 2.         0.66666667 1.55555556 4.22222222]
[2 3 3 2 1]
[7 6 5 5 6]
[0 0 1 1 1]
[2 1 2 0 0]


In [ ]:
n3 = np.array([[[1,2,3,4] , [5,4,6,6] , [2,6,5,4]],
              [[1,2,3,4] , [5,4,6,6] , [2,6,5,4]]])
print(n3)

[[[1 2 3 4]
  [5 4 6 6]
  [2 6 5 4]]

 [[1 2 3 4]
  [5 4 6 6]
  [2 6 5 4]]]


In [ ]:
print(n3.shape)
print(n3.ndim)
print(n3.size)

(2, 3, 4)
3
24


In [ ]:
print(np.sum(n3 , axis=0))

[[ 2  4  6  8]
 [10  8 12 12]
 [ 4 12 10  8]]


In [ ]:
print(np.sum(n3 , axis=1))

[[ 8 12 14 14]
 [ 8 12 14 14]]


In [ ]:
print(np.sum(n3 , axis=2))

[[10 21 17]
 [10 21 17]]


In [ ]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.randint(0,10)

9

In [ ]:
np.random.randint(0,10,(3,4))

array([[9, 1, 8, 4],
       [8, 3, 4, 0],
       [9, 7, 4, 1]])

In [ ]:
n5 = np.random.randint(0,10,(3,4))
print(n5)

[[5 9 6 6]
 [7 9 4 6]
 [8 8 9 5]]


In [ ]:
n6 = np.random.randint(0,10,(2,4))
print(n6)

[[1 7 6 7]
 [1 2 9 5]]


In [ ]:
np.vstack((n5,n6))

array([[5, 9, 6, 6],
       [7, 9, 4, 6],
       [8, 8, 9, 5],
       [1, 7, 6, 7],
       [1, 2, 9, 5]])

In [ ]:
np.concatenate((n5,n6) , axis = 0)

array([[5, 9, 6, 6],
       [7, 9, 4, 6],
       [8, 8, 9, 5],
       [1, 7, 6, 7],
       [1, 2, 9, 5]])

In [ ]:
n7 = np.random.randint(0,10,(2,2))
print(n7)

[[5 6]
 [9 7]]


In [ ]:
np.hstack((n6,n7))

array([[1, 7, 6, 7, 5, 6],
       [1, 2, 9, 5, 9, 7]])

In [ ]:
np.concatenate((n6,n7) , axis = 1)

array([[1, 7, 6, 7, 5, 6],
       [1, 2, 9, 5, 9, 7]])